version: '3'

services:
  ## Backend
  api:
    build: backend
    container_name: fastapi
    volumes:
      - ./backend:/backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo-db
    networks:
      - my-network

  ## Frontend
  client:
    build: frontend
    container_name: react
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '443:443'
      - '80:80'
    links:
      - api
    depends_on:
      - api
    networks:
      - my-network

 ## Mongo database
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - 27017:27017
    networks:
      - my-network

  ## Administration for mongo db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo-db
    networks:
      - my-network

  ## Portainer
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORTAINER_USERNAME: admin
      PORTAINER_PASSWOR: admin
    networks:
      - my-network

  ## Certbot
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email nkaskaj@gmail.com --agree-tos --no-eff-email -v -d matejkaska.me
    volumes:
      - ./frontend:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - EMAIL=nkaskaj@gmail.com
      - CERTBOT_DOMAIN=matejkaska.me
    depends_on:
      - client
    networks:
      - my-network

## Network
networks:
  my-network:
    driver: bridge